site_name: uPorta
site_url: https://uporta.com

theme:
  name: material
  language: es
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - search.suggest
    - search.highlight

plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: es
          name: Español
          default: true
          build: true
        - locale: en
          name: English
          build: true

nav:
  - Inicio: index.md
  - Blog:
      - "Diseño para la Fricción Cotidiana": blog/entrada1.md
      - "El Diseño como Puente": blog/entrada2.md
      - "Intimidad y Agilidad": blog/entrada3.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - attr_list
  - def_list
  - md_in_html
